server {
  listen 80;
  listen [::]:80;
  server_name thedivyanshupabia.com www.thedivyanshupabia.com;

  root /var/www/thedivyanshupabia.com/current;
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }

  location ~ /\. {
    deny all;
  }
}
